# Generated by Django 5.0.4 on 2025-07-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_users_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='datajoined',
            new_name='datejoined',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='stockbuy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='stocksold',
            field=models.JSONField(default=dict),
        ),
    ]
